---
title: "Distal vs. Proximal analysis"
author: "Sara Gosline"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(purrr)
library(devtools)
#library(MSnSet.utils)
if(!require(MSnSet.utils))
  devtools::install_github('PNNL-Comp-Mass-Spec/MSnSet.utils')

library(ggplot2)
library(ggfortify)
library(cowplot)
library(leapR)

source('loadHumanPancData.R')
```

## Re-calculate differnetial expression

Let's double check to see if we can find proximal vs. distal differential expression

```{r diffex}
#m3<- MSnSet(exprs = crosstab2, pData = isletMeta)

fixed.crosstab<-correctMissingProteins(fulltab)
m2<- MSnSet(exprs = fixed.crosstab, pData = isletMeta)

res.fixed <- limma_contrasts(eset = m2, model.str = "~ 0 + IsletOrNot + IsletNumber", 
                       coef.str = "IsletOrNot", contrasts = "IsletOrNotIslet - IsletOrNotNonIslet", 
                       trend = T, robust = T) #plot = T?

res.fixed <- res.fixed%>%
  mutate(signif=(adj.P.Val<0.01)&abs(logFC)>1)
#res.orig <- limma_contrasts(eset = m3, model.str = "~ 0 + IsletStatus", 
#                       coef.str = "IsletStatus", contrasts = "IsletStatusProximal - IsletStatusDistal", trend = T, robust = T) #plot = T?


```

## Do the LeapR and plot

Any pathways of interest? 

```{r pressure, echo=FALSE, message=F, warning=F}
data('krbpaths')
##map features to Gene Names
map<-read.table('uniprotMap.txt',header = TRUE)
 

doEnrich<-function(res,prefix=''){
  islet<-res%>%
    # tidyr::separate(feature,sep='_',into=c('From','spec'))%>%
    dplyr::rename(From='feature')%>%
    left_join(map)%>%
    dplyr::select(logFC,P.Value,adj.P.Val,To)%>%
    subset(!is.na(logFC))%>%
    subset(!is.na(To))%>%
    distinct()

  ##now remove dupes
  dupes<-islet$To[which(duplicated(islet$To))]

  non.dupes<-islet%>%
    subset(!To%in%dupes)

  fixed.dupes<-islet%>%
      subset(To%in%dupes)%>%
      dplyr::group_by(To,.drop=F)%>%
      dplyr::summarize(minP=min(P.Value))%>%
      left_join(islet)%>%
      subset(minP==P.Value)%>%
    dplyr::select(-minP)

  full.islet<-rbind(non.dupes,fixed.dupes)%>%
  #  tibble::column_to_rownames('To')%>%
    arrange(desc(logFC))

  rownames(full.islet)<-full.islet$To
  
  top.logfc<-min(subset(subset(full.islet,adj.P.Val<0.05),logFC>0)$logFC)
  bottom.logfc<-max(subset(subset(full.islet,adj.P.Val<0.05),logFC<0)$logFC)
    
  ###
  ##create matrix
  order.res<-leapR(datamatrix=as.data.frame(full.islet),krbpaths,'enrichment_in_order',
                   primary_columns='logFC',id_column='To')%>%
  # subset(pvalue<0.05)%>%
    subset(BH_pvalue<0.2)%>%
    dplyr::select(ingroup_n,ingroup_mean,BH_pvalue,pvalue,zscore)%>%
    arrange(pvalue)

  #print(order.res)
  p<-plotLeapR(order.res,'REACTOME')
  ggsave(paste0('REACTOME',prefix,'_enrichment.pdf'),p,width=12)
#rownames(full.islet)<-full.islet$To

  go.set.upreg<-leapR(datamatrix=as.data.frame(full.islet),gosigs,'enrichment_in_sets',
                    primary_columns='logFC',id_column='To',threshold=1,
                    greaterthan=TRUE)%>%
       subset(BH_pvalue<0.01)%>%
    dplyr::select(ingroup_n,ingroup_mean,pvalue,BH_pvalue,oddsratio)%>%
    dplyr::arrange(pvalue)

    go.set.downreg<-leapR(datamatrix=as.data.frame(full.islet),gosigs,'enrichment_in_sets',
                    primary_columns='logFC',id_column='To',threshold=(-1),
                    greaterthan=FALSE)%>%
       subset(BH_pvalue<0.05)%>%
    dplyr::select(ingroup_n,ingroup_mean,pvalue,BH_pvalue,oddsratio)%>%
    dplyr::arrange(pvalue)
    
    
  go.order.res<-leapR(datamatrix=full.islet,gosigs,'enrichment_in_order',
                      primary_columns='logFC',id_column='To')%>%
   #subset(pvalue<0.05)%>%
   subset(BH_pvalue<0.2)%>%
    dplyr::select(ingroup_n,ingroup_mean,pvalue,BH_pvalue,zscore)%>%
    arrange(pvalue)
  p<-plotLeapR(go.order.res,'GO')
  p
  ggsave(paste0('GO',prefix,'_enrichment.pdf'),p,width=12)

}

doEnrich(res.fixed,'normalized')
#doEnrich(res.orig,'unnormalized')
```

Nothing is significant when i rank by fold change, instead lets do standard fishers exact test enrichment

```{r enrichment in set}

```
