---
title: "Distance based analysis"
author: "Sara Gosline"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(purrr)
library(devtools)
#library(MSnSet.utils)
if(!require(MSnSet.utils))
  devtools::install_github('PNNL-Comp-Mass-Spec/MSnSet.utils')

library(ggplot2)
library(ggfortify)
library(cowplot)
library(leapR)
source('loadHumanPancData.R')
```

## Map to distances
get data and metadata nad join to get distance data

```{r distnace data, message=FALSE, warning=FALSE}

m2<- MSnSet(exprs = crosstab2, pData = isletMeta)



long.tab<-exprs(m2)%>%
  as.data.frame()%>%
  tibble::rownames_to_column('protein')%>%
  tidyr::pivot_longer(cols=c(1:ncol(exprs(m2))+1),
                      names_to='sample',
                      values_to='logFC')%>%
  left_join(tibble::rownames_to_column(isletMeta,'sample'))%>%
  dplyr::select(protein,`sample`,logFC,`Distance to islet`,`Islet Number`)
  
cor.vals<-long.tab%>%
  group_by(protein,`Islet Number`)%>%
  summarize(corVal=cor(logFC,`Distance to islet`,use='pairwise.complete.obs',method='pearson'))


  
cor.na.vals<-long.tab%>%
  group_by(protein,`Islet Number`)%>%
  summarize(corVal=cor(logFC,`Distance to islet`,method='spearman'))


##which ones are highly anti-correlated
```

## Gene mapping and enrichment

now we want to evaluate the enrichment of the proteins whose expression is correlated with distance (lower in islet) and anti-correlated (higher in islet) 

```{r mapping, warning=FALSE, message=FALSE}

map<-read.table('uniprotMap.txt',header = TRUE)
 
 # tidyr::separate(feature,sep='\\|',into=c('sp','id','From'))%>%
#  left_join(map)%>%

##TODO: summary table off differential expression with venn diagram
cor.names<-cor.vals%>%
  tidyr::separate(protein,sep='\\|',into=c('sp','id','From'))%>%
  left_join(map)%>%
  subset(!is.na(To))

#%>%
#  arrange(corVal)

cor.mat<-cor.names%>%
  dplyr::mutate(`Islet Number`=as.character(`Islet Number`))%>%
  tidyr::pivot_wider(names_from=`Islet Number`,values_from=corVal)#%>%
#  tibble::column_to_rownames('To')

##now remove dupes
dupes<-cor.mat$To[which(duplicated(cor.mat$To))]

cor.mat<-cor.mat%>%
  subset(!To%in%dupes)%>%
  tibble::column_to_rownames('To')

library(ggfortify)

dm <- as.matrix(cor.mat[,4:10])
keep<-apply(dm,1,function(x) !any(is.na(x)))

pc.vals<-prcomp(t(dm[keep,]))
###how do the values work in 2 dimensions?

hist(cor.names$corVal)

autoplot(pc.vals,label=TRUE)
ggsave('correlationPCA.pdf')
```

now we have all the correlation values

```{r go enrichment, message=F, warning=F}
library(leapR)
library(pheatmap)
#data("ncipid")

go.order.res<-lapply(unique(as.character(cor.names$`Islet Number`)),
                       function(x) {
                         leapR(datamatrix=cor.mat,gosigs,'enrichment_in_order',
                 primary_columns=x,minsize=10)%>%
  subset(BH_pvalue<0.05)%>%
#  dplyr::select(ingroup_n,ingroup_mean,BH_pvalue,zscore)%>%
  arrange(BH_pvalue)%>%
  mutate(image=x)%>%tibble::rownames_to_column('Pathway')
                        })

go.order.tab<-do.call(rbind,go.order.res)%>%
#  subset(BH_pvalue<0.05)%>%
  dplyr::select(Pathway,zscore,image)%>%
  mutate(Pathway=stringr::str_replace_all(Pathway," \\(GO:[0-9]*\\)",''))%>%
  tidyr::pivot_wider(names_from='image',values_from='zscore',values_fill=list(zscore=0.0))%>%
  tibble::column_to_rownames('Pathway')
  
terms<-which(apply(go.order.tab,1,function(x) length(which(x==0))<4))

pheatmap(go.order.tab[names(terms),],cellwidth = 10,cellheight=10,filename = 'goBPterms.pdf')
```

now lets do kegg
```{r KEGG enrichment, message=F, warning=F}

#data("ncipid")
data('krbpaths')


kegg.order.res<-lapply(unique(as.character(cor.names$`Islet Number`)),
                       function(x) {
                         leapR(datamatrix=cor.mat,krbpaths,'enrichment_in_order',
                 primary_columns=x,
                 minsize=5)%>%
  subset(BH_pvalue<0.05)%>%
                           
#  dplyr::select(ingroup_n,ingroup_mean,BH_pvalue,zscore)%>%
  arrange(BH_pvalue)%>%
                           
  mutate(image=x)%>%  
                           tibble::rownames_to_column('pathway')

                         })

krb.order.tab<-do.call(rbind,kegg.order.res)%>%
#  subset(BH_pvalue<0.05)%>%
  dplyr::select(zscore,image,pathway)

kegg.order.tab<-krb.order.tab[grep("KEGG",krb.order.tab$pathway),]
reac.order.tab<-krb.order.tab[grep("REAC",krb.order.tab$pathway),]

kegg.order.tab<-kegg.order.tab%>%
  mutate(pathway=stringr::str_replace_all(pathway,'_',' '))%>%
  mutate(pathway=stringr::str_replace_all(pathway,'REACTOME|KEGG|BIOCARTA',''))%>%
  mutate(pathway=tolower(pathway))%>%
  tidyr::pivot_wider(names_from='image',values_from='zscore',values_fill=list(zscore=0.0))%>%
  tibble::column_to_rownames('pathway')
  
  
reac.order.tab<-reac.order.tab%>%
  mutate(pathway=stringr::str_replace_all(pathway,'_',' '))%>%
  mutate(pathway=stringr::str_replace_all(pathway,'REACTOME|KEGG|BIOCARTA',''))%>%
  mutate(pathway=tolower(pathway))%>%
  tidyr::pivot_wider(names_from='image',values_from='zscore',values_fill=list(zscore=0.0))%>%
  tibble::column_to_rownames('pathway')
  

#terms<-which(apply(kegg.order.tab,1,function(x) length(which(x==0))<6))

pheatmap(kegg.order.tab)

pheatmap(kegg.order.tab,cellwidth = 10,cellheight=10,filename = 'keggterms.pdf')



terms<-which(apply(reac.order.tab,1,function(x) length(which(x==0))<4))

pheatmap(reac.order.tab[terms,])

pheatmap(reac.order.tab[terms,],cellwidth = 10,cellheight=10,filename = 'reacterms.pdf')

```
